Update release_generation.yml
Signed-off-by: FortiShield <161459699+FortiShield@users.noreply.github.com>

diff --git a/.github/workflows/release_generation.yml b/.github/workflows/release_generation.yml
--- a/.github/workflows/release_generation.yml
+++ b/.github/workflows/release_generation.yml
@@ -20,7 +20,13 @@ jobs:
         fetch-depth: 0
     - name: Getting Tag
       id: tag_extractor
-      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
+      run: |
+        latest_tag=$(git describe --tags --abbrev=0)
+        if [ -z "$latest_tag" ]; then
+          echo "Error: No tags found."
+          exit 1
+        fi
+        echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"
   
     - uses: ncipollo/release-action@v1
       with:
